"""create tables

Revision ID: 7be78bee1c4c
Revises: 
Create Date: 2020-02-19 13:59:57.498546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be78bee1c4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_id', sa.String(length=30), nullable=False),
    sa.Column('ko_name', sa.String(length=10), nullable=True),
    sa.Column('en_name', sa.String(length=10), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('google_id', 'en_name', name='unique_user_constraint')
    )
    op.create_table('remain_vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('number_of_years', sa.Integer(), nullable=False),
    sa.Column('total_vacation', sa.Float(), nullable=False),
    sa.Column('remain_vacation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.google_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('used_vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=True),
    sa.Column('event_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.google_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_vacation')
    op.drop_table('remain_vacation')
    op.drop_table('user')
    # ### end Alembic commands ###
